import { Validators } from '@angular/forms';

export const ACSx290form = {
         sectionA: {
           HN: [null, Validators.required],
           AN: [null, Validators.required]
         },
         sectionB: {
           PatLName: [null, [Validators.required, Validators.minLength(5), Validators.maxLength(10)]],
           PatFName: [null, Validators.required],
           PatMName: [null],
           DOB: [null, Validators.required],
           Age: [null, Validators.required],
           Gender: [null, Validators.required],
           SSN: [null, Validators.required],
           PatAddr: [null],
           PatCity: [null, Validators.required],
           PatRegion: [null, Validators.required],
           PatientCountry: [null, Validators.required],
           PermAddr: [null, Validators.required]
         },
         sectionD: {
           HeightCM: [null, [Validators.required, Validators.min(20), Validators.max(251)]],
           WeightKg: [null, [Validators.required, Validators.min(10), Validators.max(250)]],
           FHCAD: [null, Validators.required],
           Diabetes: [null, Validators.required],
           DiabCtrl: [null, Validators.required],
           Dyslip: [null, Validators.required],
           Dialysis: [null, Validators.required],
           Hypertn: [null, Validators.required],
           InfEndo: [null, Validators.required],
           InfEndTy: [null, Validators.required],
           InfEndCult: [null, Validators.required],
           TobaccoUse: [null, Validators.required],
           ChrLungD: [null, Validators.required],
           ChrLungDType: [null, Validators.required],
           PFT: [null, Validators.required],
           FEV1: [null, [Validators.required, Validators.min(10), Validators.max(200)]],
           DLCO: [null, Validators.required],
           DLCOPred: [null, [Validators.required, Validators.min(10), Validators.max(200)]],
           ABG: [null, Validators.required],
           PCO2: [null, [Validators.required, Validators.min(20), Validators.max(120)]],
           PO2: [null, [Validators.required, Validators.min(40), Validators.max(500)]],
           HmO2: [null, Validators.required],
           BDTx: [null, Validators.required],
           SlpApn: [null, Validators.required],
           Pneumonia: [null, Validators.required],
           IVDrugAb: [null, Validators.required],
           Depression: [null, Validators.required],
           Alcohol: [null, Validators.required],
           LiverDis: [null, Validators.required],
           LiverChildPugh: [null, Validators.required],
           LiverTransList: [null, Validators.required],
           LiverStatusPost: [null, Validators.required],
           ImmSupp: [null, Validators.required],
           MediastRad: [null, Validators.required],
           Cancer: [null, Validators.required],
           PVD: [null, Validators.required],
           ThAoDisease: [null, Validators.required],
           Syncope: [null, Validators.required],
           UnrespStat: [null, Validators.required],
           ChestWallDef: [null, Validators.required],
           CVD: [null, Validators.required],
           CVA: [null, Validators.required],
           CVAWhen: [null, Validators.required],
           CVDTIA: [null, Validators.required],
           CVDCarSten: [null, Validators.required],
           CVDStenRt: [null, Validators.required],
           CVDStenLft: [null, Validators.required],
           CVDPCarSurg: [null, Validators.required],
           WBC: [null, [Validators.min(100), Validators.max(99990)]],
           RFHemoglobin: [null, [Validators.min(1.0), Validators.max(50.0)]],
           Hct: [null, [Validators.min(1.0), Validators.max(99.99)]],
           Platelets: [null, [Validators.min(1000), Validators.max(900000)]],
           CreatLst: [null, [Validators.min(0.1), Validators.max(30.0)]],
           TotAlbumin: [null, [Validators.min(1.0), Validators.max(10.0)]],
           TotBlrbn: [null, [Validators.min(0.1), Validators.max(50.0)]],
           A1cLvl: [null, [Validators.min(1.0), Validators.max(20.0)]],
           HITAnti: [null],
           INR: [null, [Validators.min(0.5), Validators.max(30.0)]],
           MELDScr: [null, [Validators.min(-50), Validators.max(150)]],
           BNP: [null, [Validators.min(5), Validators.max(70000)]],
           FiveMWalkTest: [null],
           FiveMWalk1: [null, [Validators.min(1), Validators.max(100)]],
           FiveMWalk2: [null, [Validators.min(1), Validators.max(100)]],
           FiveMWalk3: [null, [Validators.min(1), Validators.max(100)]],
           SixMWalkDone: [null],
           SixMWalkDist: [null, [Validators.min(1), Validators.max(3000)]]
         },
         sectionE: {
           PrCVInt: [null, Validators.required],
           PrCAB: [null, Validators.required],
           PrValve: [null, Validators.required],
           PrValveProc1: [null, Validators.required],
           PrValveProc2: [null, Validators.required],
           PrValveProc3: [null, Validators.required],
           PrValveProc4: [null, Validators.required],
           PrValveProc5: [null, Validators.required],
           POCPCI: [null, Validators.required],
           POCPCIWhen: [null, Validators.required],
           POCPCIndSurg: [null, Validators.required],
           POCPCISt: [null, Validators.required],
           POCPCIStTy: [null, Validators.required],
           POCPCIIn: [null, Validators.required],
           POC: [null, Validators.required],
           POCInt1: [null, Validators.required],
           POCInt2: [null, Validators.required],
           POCInt3: [null, Validators.required],
           POCInt4: [null, Validators.required],
           POCInt5: [null, Validators.required],
           POCInt6: [null, Validators.required],
           POCInt7: [null, Validators.required]
         },
         sectionF: {
           PrevMI: [null, Validators.required],
           MIWhen: [null, Validators.required],
           CardSympTimeOfAdm: [null, Validators.required],
           CardSympTimeOfSurg: [null, Validators.required],
           HeartFail: [null, Validators.required],
           HeartFailTmg: [null, Validators.required],
           HeartFailType: [null, Validators.required],
           ClassNYH: [null, Validators.required],
           CarShock: [null, Validators.required],
           Resusc: [null, Validators.required],
           Arrhythmia: [null, Validators.required],
           ArrhythPPaced: [null, Validators.required],
           ArrhythVV: [null, Validators.required],
           ArrhythSSS: [null, Validators.required],
           ArrhythAFlutter: [null, Validators.required],
           ArrhythAFib: [null, Validators.required],
           ArrhythAtrFib: [null, Validators.required],
           ArrhythSecond: [null, Validators.required],
           ArrhythThird: [null, Validators.required]
         },
         sectionG: {
           MedACEI48: [null, Validators.required],
           MedAmiodarone: [null, Validators.required],
           MedBeta: [null, Validators.required],
           MedBetaTher: [null, Validators.required],
           MedCChanTher: [null, Validators.required],
           MedLongActNit: [null, Validators.required],
           MedNitIV: [null, Validators.required],
           MedOthAntiang: [null, Validators.required],
           MedADP5Days: [null, Validators.required],
           MedADPIDis: [null, Validators.required],
           MedASA: [null, Validators.required],
           MedASADis: [null, Validators.required],
           MedASAOnce: [null, Validators.required],
           MedGP: [null, Validators.required],
           MedACoag: [null, Validators.required],
           MedACMN: [null, Validators.required],
           MedCoum5Days: [null, Validators.required],
           MedCoum5Dis: [null, Validators.required],
           MedXa5Days: [null, Validators.required],
           MedXa5DDis: [null, Validators.required],
           MedNOAC5Days: [null, Validators.required],
           MedNOACDisc: [null, Validators.required],
           MedThromIn5Days: [null, Validators.required],
           MedThromInDisc: [null, Validators.required],
           MedThrom: [null, Validators.required],
           MedInotr: [null, Validators.required],
           MedLipid: [null, Validators.required],
           MedLipType: [null, Validators.required],
           MedSter: [null, Validators.required]
         },
         sectionH: {
           CarCathPer: [null, Validators.required],
           CarCathDt: [null, Validators.required],
           CorAnatDisKnown: [null, Validators.required],
           Dominance: [null, Validators.required],
           StenSource: [null, Validators.required],
           NumDisV: [null, Validators.required],
           PctStenKnown: [null, Validators.required],
           GraftsPrsnt: [null, Validators.required],
           StentPrsnt: [null, Validators.required],
           FFRPerf: [null, Validators.required],
           IFRPerf: [null, Validators.required],

           // cath finding
           PctStenLMain: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           GrftStenLMain: [null, Validators.required],
           StntStenLMain: [null, Validators.required],
           FFRLMain: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],
           IFRLMain: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],

           PctStenProxLAD: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           GrftStenProxLAD: [null, Validators.required],
           StntStenProxLAD: [null, Validators.required],
           FFRProxLAD: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],
           IFRProxLAD: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],

           PctStenMidLAD: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           GrftStenMidLAD: [null, Validators.required],
           StntStenMidLAD: [null, Validators.required],
           FFRMidLAD: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],
           IFRMidLAD: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],

           PctStenDistLAD: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           GrftStenDistLAD: [null, Validators.required],
           StntStenDistLAD: [null, Validators.required],
           FFRDistLAD: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],
           IFRDistLAD: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],

           PctStenDiag1: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           GrftStenDiag1: [null, Validators.required],
           StntStenDiag1: [null, Validators.required],
           FFRDiag1: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],
           IFRDiag1: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],

           PctStenDiag2: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           GrftStenDiag2: [null, Validators.required],
           StntStenDiag2: [null, Validators.required],
           FFRDiag2: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],
           IFRDiag2: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],

           PctStenDiag3: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           GrftStenDiag3: [null, Validators.required],
           StntStenDiag3: [null, Validators.required],
           FFRDiag3: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],
           IFRDiag3: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],

           PctStenCircflx: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           GrftStenCircflx: [null, Validators.required],
           StntStenCircflx: [null, Validators.required],
           FFRCircflx: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],
           IFRCircflx: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],

           PctStenOM1: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           GrftStenOM1: [null, Validators.required],
           StntStenOM1: [null, Validators.required],
           FFROM1: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],
           IFROM1: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],

           PctStenOM2: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           GrftStenOM2: [null, Validators.required],
           StntStenOM2: [null, Validators.required],
           FFROM2: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],
           IFROM2: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],

           PctStenOM3: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           GrftStenOM3: [null, Validators.required],
           StntStenOM3: [null, Validators.required],
           FFROM3: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],
           IFROM3: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],

           PctStenRamus: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           GrftStenRamus: [null, Validators.required],
           StntStenRamus: [null, Validators.required],
           FFRRamus: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],
           IFRRamus: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],

           PctStenRCA: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           GrftStenRCA: [null, Validators.required],
           StntStenRCA: [null, Validators.required],
           FFRRCA: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],
           IFRRCA: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],

           PctStenAM: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           GrftStenAM: [null, Validators.required],
           StntStenAM: [null, Validators.required],
           FFRAM: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],
           IFRAM: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],

           PctStenPDA: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           GrftStenPDA: [null, Validators.required],
           StntStenPDA: [null, Validators.required],
           FFRPDA: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],
           IFRPDA: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],

           PctStenPLB: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           GrftStenPLB: [null, Validators.required],
           StntStenPLB: [null, Validators.required],
           FFRPLB: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],
           IFRPLB: [null, [Validators.required, Validators.min(0.0), Validators.max(1.0)]],

           SyntaxScrKnown: [null, Validators.required],
           SyntaxScr: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           StressTst: [null, Validators.required],
           StrsTstRes: [null, Validators.required],
           HDEFD: [null, Validators.required],
           HDEF: [null, [Validators.required, Validators.min(1), Validators.max(99)]],
           DimAvail: [null, Validators.required],
           LVSD: [null, [Validators.required, Validators.min(0.0), Validators.max(99.0)]],
           LVEDD: [null, [Validators.required, Validators.min(20.0), Validators.max(100.0)]],
           PASYSMeas: [null, Validators.required],
           PASYS: [null, [Validators.required, Validators.min(10), Validators.max(150)]],

           VDInsufA: [null, Validators.required],
           VDAVEccJet: [null, Validators.required],
           VDAort: [null, Validators.required],
           VDStenA: [null, Validators.required],
           AoHemoDatAvail: [null, Validators.required],
           VDAoVA: [null, [Validators.required, Validators.min(0.2), Validators.max(5.0)]],
           VDGradA: [null, [Validators.required, Validators.min(0), Validators.max(200)]],
           VDVMax: [null, [Validators.required, Validators.min(0), Validators.max(8)]],
           VDAoPrimEt: [null, Validators.required],
           VDAoSievers: [null, Validators.required],

           VDInsufM: [null, Validators.required],
           VDMVEccJet: [null, Validators.required],
           VDMit: [null, Validators.required],
           VDStenM: [null, Validators.required],
           MiHemoDatAvail: [null, Validators.required],
           VDMVA: [null, [Validators.required, Validators.min(0.6), Validators.max(6.0)]],
           VDGradM: [null, [Validators.required, Validators.min(0), Validators.max(30)]],
           VDMiPrimEt: [null, Validators.required],
           VDMiPrimLes: [null, Validators.required],

           VDInsufT: [null, Validators.required],
           VDTrAnnMeas: [null, Validators.required],
           VDTrAnnSize: [null, [Validators.required, Validators.min(1.5), Validators.max(10.0)]],
           VDTr: [null, Validators.required],
           VDStenT: [null, Validators.required],
           VDTrPrimEt: [null, Validators.required],

           VDInsufP: [null, Validators.required],
           VDPulm: [null, Validators.required],
           RVEDDKnown: [null, Validators.required],
           RVEDD: [null, [Validators.required, Validators.min(0.5), Validators.max(5.0)]],
           VDStenP: [null, Validators.required],
           PuHemoDatAvail: [null, Validators.required],
           VDGradP: [null, [Validators.required, Validators.min(0), Validators.max(200)]],
           VDPuEt: [null, Validators.required]
         },
         sectionI: {
           Surgeon: [null, Validators.required],
           RiskDiscussed: [null, Validators.required],
           STSscore: [null, Validators.required],
           Incidenc: [null, Validators.required],
           Status: [null, Validators.required],
           UrgEmergRsn: [null, Validators.required],

           PCancCase: [null, Validators.required],
           PCancCaseDt: [null, Validators.required],
           PCancCaseTmg: [null, Validators.required],
           PCancCaseRsn: [null, Validators.required],
           PCancCaseCAB: [null, Validators.required],
           PCancCaseMech: [null, Validators.required],
           PCancCaseONC: [null, Validators.required],
           PCancCaseValSur: [null, Validators.required],
           PCancCaseValTrans: [null, Validators.required],
           PCancCaseOC: [null, Validators.required],

           CCancCase: [null, Validators.required],
           CCancCaseTmg: [null, Validators.required],
           CCancCaseRsn: [null, Validators.required],
           CCancCaseCAB: [null, Validators.required],
           CCancCaseMech: [null, Validators.required],
           CCancCaseONC: [null, Validators.required],
           CCancCaseValSur: [null, Validators.required],
           CCancCaseValTrans: [null, Validators.required],
           CCancCaseOC: [null, Validators.required],

           OPApp: [null, Validators.required],
           ApproachCon: [null, Validators.required],
           Robotic: [null, Validators.required],
           RobotTim: [null, Validators.required],

           OpCAB: [null, Validators.required],
           OpValve: [null, Validators.required],
           OpValSurgInput: [null, Validators.required],
           AortProc: [null, Validators.required],
           AortProcSurgInput: [null, Validators.required],
           OpOCard: [null, Validators.required],
           AFibProc: [null, Validators.required],
           AFibProcSurgInput: [null, Validators.required],
           OpONCard: [null, Validators.required],

           OREntryDT: [null, Validators.required],
           ORExitDT: [null, Validators.required],
           GenAnes: [null, Validators.required],
           ProcSed: [null, Validators.required],
           Intubate: [null, Validators.required],
           IntubateDT: [null, Validators.required],
           ExtubateDT: [null, Validators.required],
           SIStartDT: [null, Validators.required],
           SIStopDT: [null, Validators.required],
           AnesEndDT: [null, Validators.required],
           AbxSelect: [null, Validators.required],
           AbxTiming: [null, Validators.required],
           AbxDisc: [null, Validators.required],
           AddIntraopPAnti: [null, Validators.required],
           TempMeas: [null, Validators.required],
           LwstTemp: [null, [Validators.required, Validators.min(5.0), Validators.max(40.0)]],
           LwstTempSrc: [null, Validators.required],
           LwstIntraHemo: [null, [Validators.required, Validators.min(1.0), Validators.max(50.0)]],
           LwstHct: [null, [Validators.required, Validators.min(1.0), Validators.max(99.99)]],
           HighIntraGlu: [null, [Validators.required, Validators.min(40), Validators.max(2000)]],

           CPBUtil: [null, Validators.required],
           CPBCmb: [null, Validators.required],
           CPBCmbR: [null, Validators.required],

           CanArtStAort: [null, Validators.required],
           CanArtStFem: [null, Validators.required],
           CanArtStAx: [null, Validators.required],
           CanArtStInn: [null, Validators.required],
           CanArtStO: [null, Validators.required],

           CanVenStFem: [null, Validators.required],
           CanVenStJug: [null, Validators.required],
           CanVenStRtA: [null, Validators.required],
           CanVenStLfA: [null, Validators.required],
           CanVenStPulm: [null, Validators.required],
           CanVenStBi: [null, Validators.required],
           CanVenStOth: [null, Validators.required],

           PerfusTm: [null, Validators.required],
           CircArr: [null, Validators.required],
           DHCATm: [null, [Validators.required, Validators.min(0), Validators.max(300)]],
           CPerfUtil: [null, Validators.required],
           CPerfTime: [null, [Validators.required, Validators.min(1), Validators.max(999)]],
           CPerfTyp: [null, Validators.required],
           TotCircArrTm: [null, Validators.required],

           AortOccl: [null, Validators.required],
           XClampTm: [null, [Validators.required, Validators.min(0), Validators.max(600)]],
           CplegiaDeliv: [null, Validators.required],
           CplegiaType: [null, Validators.required],
           CerOxUsed: [null, Validators.required],
           ConCalc: [null, Validators.required],
           AsmtAscAA: [null, Validators.required],
           AsmtAoDxMeth: [null, Validators.required],
           AsmtAoDx: [null, Validators.required],
           AsmtAPln: [null, Validators.required],

           IBldProdRef: [null, Validators.required],
           IBldProd: [null, Validators.required],
           IBdRBCU: [null, [Validators.required, Validators.min(0), Validators.max(99)]],
           IBdFFPU: [null, [Validators.required, Validators.min(0), Validators.max(99)]],
           IBdPlatU: [null, [Validators.required, Validators.min(0), Validators.max(99)]],
           IBdCryoU: [null, [Validators.required, Validators.min(0), Validators.max(99)]],

           IntraClotFact: [null, Validators.required],
           IntraopProComCon: [null, Validators.required],
           IMedEACA: [null, Validators.required],
           IMedTran: [null, Validators.required],

           InOpTEE: [null, Validators.required],
           PRepAR: [null, Validators.required],
           PRepAGradM: [null, [Validators.required, Validators.min(0), Validators.max(200)]],
           PRepAPVL: [null, Validators.required],
           PRepMR: [null, Validators.required],
           PRepMGradM: [null, [Validators.required, Validators.min(0), Validators.max(30)]],
           PRepMPVL: [null, Validators.required],
           PRepTR: [null, Validators.required],
           PRepTGradM: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
           PRepTPVL: [null, Validators.required],
           PPEFMeas: [null, Validators.required],
           PPEF: [null, [Validators.required, Validators.min(1.0), Validators.max(99.0)]],
           PPPlanedPCI: [null, Validators.required]
         },
         sectionJ: {
           IMAUsed: [null, Validators.required],
           NumIMADA: [null, [Validators.required, Validators.min(0), Validators.max(6)]],
         },
         sectionK: {},
         sectionL: {},
         sectionL2: {},
         sectionM: {},
         sectionM1: {},
         sectionM2: {},
         sectionM3: {},
         sectionN: {},
         sectionO: {},
         sectionP: {},
         sectionQ: {},
         sectionR: {}
       };
