import { FormConditions } from '../registry.model';

export const conditions: FormConditions = {
         sectionA: [],
         sectionB: [],
         sectionD: [
           { control: 'DiabCtrl', parentControl: 'Diabetes', conditions: ['Yes'] },
           { control: 'InfEndTy', parentControl: 'InfEndo', conditions: ['Yes'] },
           { control: 'InfEndCult', parentControl: 'InfEndo', conditions: ['Yes'] },
           { control: 'ChrLungDType', parentControl: 'ChrLungD', conditions: ['Mild', 'Moderate', 'Severe'] },
           { control: 'FEV1', parentControl: 'PFT', conditions: ['Yes'] },
           { control: 'DLCO', parentControl: 'PFT', conditions: ['Yes'] },
           { control: 'DLCOPred', parentControl: 'DLCO', conditions: ['Yes'] },
           { control: 'PCO2', parentControl: 'ABG', conditions: ['Yes'] },
           { control: 'PO2', parentControl: 'ABG', conditions: ['Yes'] },
           { control: 'LiverChildPugh', parentControl: 'LiverDis', conditions: ['Yes'] },
           { control: 'LiverTransList', parentControl: 'LiverDis', conditions: ['Yes'] },
           { control: 'LiverStatusPost', parentControl: 'LiverDis', conditions: ['Yes'] },
           { control: 'CVA', parentControl: 'CVD', conditions: ['Yes'] },
           { control: 'CVAWhen', parentControl: 'CVA', conditions: ['Yes'] },
           { control: 'CVDTIA', parentControl: 'CVD', conditions: ['Yes'] },
           { control: 'CVDCarSten', parentControl: 'CVD', conditions: ['Yes'] },
           { control: 'CVDStenRt', parentControl: 'CVDCarSten', conditions: ['Right', 'Both'] },
           { control: 'CVDStenLft', parentControl: 'CVDCarSten', conditions: ['Left', 'Both'] },
           { control: 'CVDPCarSurg', parentControl: 'CVD', conditions: ['Yes'] },
           { control: 'FiveMWalk1', parentControl: 'FiveMWalkTest', conditions: ['Yes'] },
           { control: 'FiveMWalk2', parentControl: 'FiveMWalkTest', conditions: ['Yes'] },
           { control: 'FiveMWalk3', parentControl: 'FiveMWalkTest', conditions: ['Yes'] },
           { control: 'SixMWalkDist', parentControl: 'SixMWalkDone', conditions: ['Yes'] }
         ],
         sectionE: [
           { control: 'PrCAB', parentControl: 'PrCVInt', conditions: ['Yes'] },
           { control: 'PrValve', parentControl: 'PrCVInt', conditions: ['Yes'] },
           { control: 'PrValveProc1', parentControl: 'PrValve', conditions: ['Yes'] },
           { control: 'PrValveProc2', parentControl: 'PrValve', conditions: ['Yes'] },
           {
             control: 'PrValveProc3',
             parentControl: 'PrValveProc2',
             conditions: ['!', 'No additional valve procedure(s)']
           },
           {
             control: 'PrValveProc4',
             parentControl: 'PrValveProc3',
             conditions: ['!', 'No additional valve procedure(s)']
           },
           {
             control: 'PrValveProc5',
             parentControl: 'PrValveProc4',
             conditions: ['!', 'No additional valve procedure(s)']
           },
           { control: 'POCPCI', parentControl: 'PrCVInt', conditions: ['Yes'] },
           { control: 'POCPCIWhen', parentControl: 'POCPCI', conditions: ['Yes'] },
           {
             control: 'POCPCIndSurg',
             parentControl: 'POCPCIWhen',
             conditions: ['Yes, at this facility', 'Yes, at some other acute care facility']
           },
           { control: 'POCPCISt', parentControl: 'POCPCI', conditions: ['Yes'] },
           { control: 'POCPCIStTy', parentControl: 'POCPCISt', conditions: ['Yes'] },
           { control: 'POCPCIIn', parentControl: 'POCPCI', conditions: ['Yes'] },
           { control: 'POC', parentControl: 'PrCVInt', conditions: ['Yes'] },
           { control: 'POCInt1', parentControl: 'POC', conditions: ['Yes'] },
           { control: 'POCInt2', parentControl: 'POC', conditions: ['Yes'] },
           { control: 'POCInt3', parentControl: 'POCInt2', conditions: ['!', 'No additional interventions'] },
           { control: 'POCInt4', parentControl: 'POCInt3', conditions: ['!', 'No additional interventions'] },
           { control: 'POCInt5', parentControl: 'POCInt4', conditions: ['!', 'No additional interventions'] },
           { control: 'POCInt6', parentControl: 'POCInt5', conditions: ['!', 'No additional interventions'] },
           { control: 'POCInt7', parentControl: 'POCInt6', conditions: ['!', 'No additional interventions'] }
         ],
         sectionF: [
           { control: 'MIWhen', parentControl: 'PrevMI', conditions: ['Yes'] },
           { control: 'HeartFailTmg', parentControl: 'HeartFail', conditions: ['Yes'] },
           { control: 'HeartFailType', parentControl: 'HeartFail', conditions: ['Yes'] },
           { control: 'ClassNYH', parentControl: 'HeartFail', conditions: ['Yes'] },
           { control: 'ArrhythPPaced', parentControl: 'Arrhythmia', conditions: ['Yes'] },
           { control: 'ArrhythVV', parentControl: 'Arrhythmia', conditions: ['Yes'] },
           { control: 'ArrhythSSS', parentControl: 'Arrhythmia', conditions: ['Yes'] },
           { control: 'ArrhythAFlutter', parentControl: 'Arrhythmia', conditions: ['Yes'] },
           { control: 'ArrhythAtrFib', parentControl: 'Arrhythmia', conditions: ['Yes'] },
           {
             control: 'ArrhythAFib',
             parentControl: 'ArrhythAtrFib',
             conditions: ['Remote (> 30 days preop)', 'Recent (<= 30 days preop)']
           },
           { control: 'ArrhythSecond', parentControl: 'Arrhythmia', conditions: ['Yes'] },
           { control: 'ArrhythThird', parentControl: 'Arrhythmia', conditions: ['Yes'] }
         ],
         sectionG: [
           { control: 'MedADPIDis', parentControl: 'MedADP5Days', conditions: ['Yes'] },
           { control: 'MedASADis', parentControl: 'MedASA', conditions: ['Yes'] },
           { control: 'MedASAOnce', parentControl: 'MedASA', conditions: ['Yes'] },
           { control: 'MedACMN', parentControl: 'MedACoag', conditions: ['Yes'] },
           { control: 'MedCoum5Dis', parentControl: 'MedCoum5Days', conditions: ['Yes'] },
           { control: 'MedXa5DDis', parentControl: 'MedXa5Days', conditions: ['Yes'] },
           { control: 'MedNOACDisc', parentControl: 'MedNOAC5Days', conditions: ['Yes'] },
           { control: 'MedThromInDisc', parentControl: 'MedThromIn5Days', conditions: ['Yes'] },
           { control: 'MedLipType', parentControl: 'MedLipid', conditions: ['Yes'] }
         ],
         sectionH: [
           { control: 'CarCathDt', parentControl: 'CarCathPer', conditions: ['Yes'] },
           { control: 'Dominance', parentControl: 'CorAnatDisKnown', conditions: ['Yes'] },
           { control: 'StenSource', parentControl: 'CorAnatDisKnown', conditions: ['Yes'] },
           { control: 'NumDisV', parentControl: 'CorAnatDisKnown', conditions: ['Yes'] },
           { control: 'H:coronary', parentControl: 'NumDisV', conditions: ['One', 'Two', 'Three'] },
           { control: 'PctStenKnown', parentControl: 'NumDisV', conditions: ['One', 'Two', 'Three'] },
           { control: 'GraftsPrsnt', parentControl: 'NumDisV', conditions: ['One', 'Two', 'Three'] },
           { control: 'StentPrsnt', parentControl: 'NumDisV', conditions: ['One', 'Two', 'Three'] },
           { control: 'FFRPerf', parentControl: 'NumDisV', conditions: ['One', 'Two', 'Three'] },
           { control: 'IFRPerf', parentControl: 'NumDisV', conditions: ['One', 'Two', 'Three'] },

           // cath result
           { control: 'H:cathresult0', parentControl: 'NumDisV', conditions: ['One', 'Two', 'Three'] },

           { control: 'PctStenLMain', parentControl: 'PctStenKnown', conditions: ['Yes'] },
           { control: 'GrftStenLMain', parentControl: 'GraftsPrsnt', conditions: ['Yes'] },
           { control: 'StntStenLMain', parentControl: 'StentPrsnt', conditions: ['Yes'] },
           { control: 'FFRLMain', parentControl: 'FFRPerf', conditions: ['Yes'] },
           { control: 'IFRLMain', parentControl: 'IFRPerf', conditions: ['Yes'] },

           { control: 'PctStenProxLAD', parentControl: 'PctStenKnown', conditions: ['Yes'] },
           { control: 'GrftStenProxLAD', parentControl: 'GraftsPrsnt', conditions: ['Yes'] },
           { control: 'StntStenProxLAD', parentControl: 'StentPrsnt', conditions: ['Yes'] },
           { control: 'FFRProxLAD', parentControl: 'FFRPerf', conditions: ['Yes'] },
           { control: 'IFRProxLAD', parentControl: 'IFRPerf', conditions: ['Yes'] },

           { control: 'PctStenMidLAD', parentControl: 'PctStenKnown', conditions: ['Yes'] },
           { control: 'GrftStenMidLAD', parentControl: 'GraftsPrsnt', conditions: ['Yes'] },
           { control: 'StntStenMidLAD', parentControl: 'StentPrsnt', conditions: ['Yes'] },
           { control: 'FFRMidLAD', parentControl: 'FFRPerf', conditions: ['Yes'] },
           { control: 'IFRMidLAD', parentControl: 'IFRPerf', conditions: ['Yes'] },

           { control: 'PctStenDistLAD', parentControl: 'PctStenKnown', conditions: ['Yes'] },
           { control: 'GrftStenDistLAD', parentControl: 'GraftsPrsnt', conditions: ['Yes'] },
           { control: 'StntStenDistLAD', parentControl: 'StentPrsnt', conditions: ['Yes'] },
           { control: 'FFRDistLAD', parentControl: 'FFRPerf', conditions: ['Yes'] },
           { control: 'IFRDistLAD', parentControl: 'IFRPerf', conditions: ['Yes'] },

           { control: 'PctStenDiag1', parentControl: 'PctStenKnown', conditions: ['Yes'] },
           { control: 'GrftStenDiag1', parentControl: 'GraftsPrsnt', conditions: ['Yes'] },
           { control: 'StntStenDiag1', parentControl: 'StentPrsnt', conditions: ['Yes'] },
           { control: 'FFRDiag1', parentControl: 'FFRPerf', conditions: ['Yes'] },
           { control: 'IFRDiag1', parentControl: 'IFRPerf', conditions: ['Yes'] },

           { control: 'PctStenDiag2', parentControl: 'PctStenKnown', conditions: ['Yes'] },
           { control: 'GrftStenDiag2', parentControl: 'GraftsPrsnt', conditions: ['Yes'] },
           { control: 'StntStenDiag2', parentControl: 'StentPrsnt', conditions: ['Yes'] },
           { control: 'FFRDiag2', parentControl: 'FFRPerf', conditions: ['Yes'] },
           { control: 'IFRDiag2', parentControl: 'IFRPerf', conditions: ['Yes'] },

           { control: 'PctStenDiag3', parentControl: 'PctStenKnown', conditions: ['Yes'] },
           { control: 'GrftStenDiag3', parentControl: 'GraftsPrsnt', conditions: ['Yes'] },
           { control: 'StntStenDiag3', parentControl: 'StentPrsnt', conditions: ['Yes'] },
           { control: 'FFRDiag3', parentControl: 'FFRPerf', conditions: ['Yes'] },
           { control: 'IFRDiag3', parentControl: 'IFRPerf', conditions: ['Yes'] },

           { control: 'PctStenCircflx', parentControl: 'PctStenKnown', conditions: ['Yes'] },
           { control: 'GrftStenCircflx', parentControl: 'GraftsPrsnt', conditions: ['Yes'] },
           { control: 'StntStenCircflx', parentControl: 'StentPrsnt', conditions: ['Yes'] },
           { control: 'FFRCircflx', parentControl: 'FFRPerf', conditions: ['Yes'] },
           { control: 'IFRCircflx', parentControl: 'IFRPerf', conditions: ['Yes'] },

           { control: 'PctStenOM1', parentControl: 'PctStenKnown', conditions: ['Yes'] },
           { control: 'GrftStenOM1', parentControl: 'GraftsPrsnt', conditions: ['Yes'] },
           { control: 'StntStenOM1', parentControl: 'StentPrsnt', conditions: ['Yes'] },
           { control: 'FFROM1', parentControl: 'FFRPerf', conditions: ['Yes'] },
           { control: 'IFROM1', parentControl: 'IFRPerf', conditions: ['Yes'] },

           { control: 'PctStenOM2', parentControl: 'PctStenKnown', conditions: ['Yes'] },
           { control: 'GrftStenOM2', parentControl: 'GraftsPrsnt', conditions: ['Yes'] },
           { control: 'StntStenOM2', parentControl: 'StentPrsnt', conditions: ['Yes'] },
           { control: 'FFROM2', parentControl: 'FFRPerf', conditions: ['Yes'] },
           { control: 'IFROM2', parentControl: 'IFRPerf', conditions: ['Yes'] },

           { control: 'PctStenOM3', parentControl: 'PctStenKnown', conditions: ['Yes'] },
           { control: 'GrftStenOM3', parentControl: 'GraftsPrsnt', conditions: ['Yes'] },
           { control: 'StntStenOM3', parentControl: 'StentPrsnt', conditions: ['Yes'] },
           { control: 'FFROM3', parentControl: 'FFRPerf', conditions: ['Yes'] },
           { control: 'IFROM3', parentControl: 'IFRPerf', conditions: ['Yes'] },

           { control: 'PctStenRamus', parentControl: 'PctStenKnown', conditions: ['Yes'] },
           { control: 'GrftStenRamus', parentControl: 'GraftsPrsnt', conditions: ['Yes'] },
           { control: 'StntStenRamus', parentControl: 'StentPrsnt', conditions: ['Yes'] },
           { control: 'FFRRamus', parentControl: 'FFRPerf', conditions: ['Yes'] },
           { control: 'IFRRamus', parentControl: 'IFRPerf', conditions: ['Yes'] },

           { control: 'PctStenRCA', parentControl: 'PctStenKnown', conditions: ['Yes'] },
           { control: 'GrftStenRCA', parentControl: 'GraftsPrsnt', conditions: ['Yes'] },
           { control: 'StntStenRCA', parentControl: 'StentPrsnt', conditions: ['Yes'] },
           { control: 'FFRRCA', parentControl: 'FFRPerf', conditions: ['Yes'] },
           { control: 'IFRRCA', parentControl: 'IFRPerf', conditions: ['Yes'] },

           { control: 'PctStenAM', parentControl: 'PctStenKnown', conditions: ['Yes'] },
           { control: 'GrftStenAM', parentControl: 'GraftsPrsnt', conditions: ['Yes'] },
           { control: 'StntStenAM', parentControl: 'StentPrsnt', conditions: ['Yes'] },
           { control: 'FFRAM', parentControl: 'FFRPerf', conditions: ['Yes'] },
           { control: 'IFRAM', parentControl: 'IFRPerf', conditions: ['Yes'] },

           { control: 'PctStenPDA', parentControl: 'PctStenKnown', conditions: ['Yes'] },
           { control: 'GrftStenPDA', parentControl: 'GraftsPrsnt', conditions: ['Yes'] },
           { control: 'StntStenPDA', parentControl: 'StentPrsnt', conditions: ['Yes'] },
           { control: 'FFRPDA', parentControl: 'FFRPerf', conditions: ['Yes'] },
           { control: 'IFRPDA', parentControl: 'IFRPerf', conditions: ['Yes'] },

           { control: 'PctStenPLB', parentControl: 'PctStenKnown', conditions: ['Yes'] },
           { control: 'GrftStenPLB', parentControl: 'GraftsPrsnt', conditions: ['Yes'] },
           { control: 'StntStenPLB', parentControl: 'StentPrsnt', conditions: ['Yes'] },
           { control: 'FFRPLB', parentControl: 'FFRPerf', conditions: ['Yes'] },
           { control: 'IFRPLB', parentControl: 'IFRPerf', conditions: ['Yes'] },

           { control: 'SyntaxScr', parentControl: 'SyntaxScrKnown', conditions: ['Yes'] },
           { control: 'StrsTstRes', parentControl: 'StressTst', conditions: ['Yes'] },
           { control: 'HDEF', parentControl: 'HDEFD', conditions: ['Yes'] },
           { control: 'LVSD', parentControl: 'DimAvail', conditions: ['Yes'] },
           { control: 'LVEDD', parentControl: 'DimAvail', conditions: ['Yes'] },
           { control: 'PASYS', parentControl: 'PASYSMeas', conditions: ['Yes'] },

           // Aortic valve
           { control: 'VDAVEccJet', parentControl: 'VDInsufA', conditions: ['!', 'None'] },
           { control: 'VDStenA', parentControl: 'VDAort', conditions: ['Yes'] },
           { control: 'AoHemoDatAvail', parentControl: 'VDStenA', conditions: ['Yes'] },
           { control: 'VDAoVA', parentControl: 'AoHemoDatAvail', conditions: ['Yes'] },
           { control: 'VDGradA', parentControl: 'AoHemoDatAvail', conditions: ['Yes'] },
           { control: 'VDVMax', parentControl: 'AoHemoDatAvail', conditions: ['Yes'] },
           { control: 'VDAoPrimEt', parentControl: 'VDAort', conditions: ['Yes'] },
           { control: 'VDAoSievers', parentControl: 'VDAoPrimEt', conditions: ['Bicuspid valve disease'] },

           // Mitral valve
           { control: 'VDMVEccJet', parentControl: 'VDInsufM', conditions: ['!', 'None'] },
           { control: 'VDStenM', parentControl: 'VDMit', conditions: ['Yes'] },
           { control: 'MiHemoDatAvail', parentControl: 'VDStenM', conditions: ['Yes'] },
           { control: 'VDMVA', parentControl: 'MiHemoDatAvail', conditions: ['Yes'] },
           { control: 'VDGradM', parentControl: 'MiHemoDatAvail', conditions: ['Yes'] },
           { control: 'VDMiPrimEt', parentControl: 'VDMit', conditions: ['Yes'] },
           { control: 'VDMiPrimLes', parentControl: 'VDMit', conditions: ['Yes'] },

           // Tricuspid valve
           { control: 'VDTrAnnSize', parentControl: 'VDTrAnnMeas', conditions: ['Yes'] },
           { control: 'VDStenT', parentControl: 'VDTr', conditions: ['Yes'] },
           { control: 'VDTrPrimEt', parentControl: 'VDTr', conditions: ['Yes'] },

           // Pulmonic valve
           { control: 'RVEDDKnown', parentControl: 'VDPulm', conditions: ['Yes'] },
           { control: 'RVEDD', parentControl: 'RVEDDKnown', conditions: ['Yes'] },
           { control: 'VDStenP', parentControl: 'VDPulm', conditions: ['Yes'] },
           { control: 'PuHemoDatAvail', parentControl: 'VDStenP', conditions: ['Yes'] },
           { control: 'VDGradP', parentControl: 'PuHemoDatAvail', conditions: ['Yes'] },
           { control: 'VDPuEt', parentControl: 'VDPulm', conditions: ['Yes'] }
         ],
         sectionI: [
           {
             control: 'STSscore',
             parentControl: 'RiskDiscussed',
             conditions: [
               'Yes, STS score was calculated, discussed and documented',
               'No, STS score was available but not discussed or documented'
             ]
           },
           { control: 'UrgEmergRsn', parentControl: 'Status', conditions: ['Urgent', 'Emergent'] },

           { control: 'PCancCaseDt', parentControl: 'PCancCase', conditions: ['Yes'] },
           { control: 'PCancCaseTmg', parentControl: 'PCancCase', conditions: ['Yes'] },
           { control: 'PCancCaseRsn', parentControl: 'PCancCase', conditions: ['Yes'] },
           { control: 'I:planPreProd', parentControl: 'PCancCase', conditions: ['Yes'] },
           { control: 'PCancCaseCAB', parentControl: 'PCancCase', conditions: ['Yes'] },
           { control: 'PCancCaseMech', parentControl: 'PCancCase', conditions: ['Yes'] },
           { control: 'PCancCaseONC', parentControl: 'PCancCase', conditions: ['Yes'] },
           { control: 'PCancCaseValSur', parentControl: 'PCancCase', conditions: ['Yes'] },
           { control: 'PCancCaseValTrans', parentControl: 'PCancCase', conditions: ['Yes'] },
           { control: 'PCancCaseOC', parentControl: 'PCancCase', conditions: ['Yes'] },

           { control: 'CCancCaseTmg', parentControl: 'CCancCase', conditions: ['Yes'] },
           { control: 'CCancCaseRsn', parentControl: 'CCancCase', conditions: ['Yes'] },
           { control: 'I:planProd', parentControl: 'CCancCase', conditions: ['Yes'] },
           { control: 'CCancCaseCAB', parentControl: 'CCancCase', conditions: ['Yes'] },
           { control: 'CCancCaseMech', parentControl: 'CCancCase', conditions: ['Yes'] },
           { control: 'CCancCaseONC', parentControl: 'CCancCase', conditions: ['Yes'] },
           { control: 'CCancCaseValSur', parentControl: 'CCancCase', conditions: ['Yes'] },
           { control: 'CCancCaseValTrans', parentControl: 'CCancCase', conditions: ['Yes'] },
           { control: 'CCancCaseOC', parentControl: 'CCancCase', conditions: ['Yes'] },

           { control: 'RobotTim', parentControl: 'Robotic', conditions: ['Yes'] },
           { control: 'OpValSurgInput', parentControl: 'OpValve', conditions: ['Yes'] },
           { control: 'AortProcSurgInput', parentControl: 'AortProc', conditions: ['Yes'] },
           { control: 'AFibProcSurgInput', parentControl: 'AFibProc', conditions: ['Yes'] },
           { control: 'ProcSed', parentControl: 'GenAnes', conditions: ['No'] },
           { control: 'Intubate', parentControl: 'GenAnes', conditions: ['Yes'] },
           {
             control: 'IntubateDT',
             parentControl: 'Intubate',
             conditions: ['Yes, prior to entering OR for this procedure', 'Yes, in OR for this procedure']
           },
           {
             control: 'ExtubateDT',
             parentControl: 'Intubate',
             conditions: ['Yes, prior to entering OR for this procedure', 'Yes, in OR for this procedure']
           },
           { control: 'LwstTemp', parentControl: 'TempMeas', conditions: ['Yes'] },
           { control: 'LwstTempSrc', parentControl: 'TempMeas', conditions: ['Yes'] },

           { control: 'CPBCmb', parentControl: 'CPBUtil', conditions: ['Combination'] },
           { control: 'CPBCmbR', parentControl: 'CPBCmb', conditions: ['Unplanned'] },

           { control: 'I:artCannSite', parentControl: 'CPBUtil', conditions: ['Combination', 'Full'] },
           { control: 'CanArtStAort', parentControl: 'CPBUtil', conditions: ['Combination', 'Full'] },
           { control: 'CanArtStFem', parentControl: 'CPBUtil', conditions: ['Combination', 'Full'] },
           { control: 'CanArtStAx', parentControl: 'CPBUtil', conditions: ['Combination', 'Full'] },
           { control: 'CanArtStInn', parentControl: 'CPBUtil', conditions: ['Combination', 'Full'] },
           { control: 'CanArtStO', parentControl: 'CPBUtil', conditions: ['Combination', 'Full'] },

           { control: 'I:venCannSite', parentControl: 'CPBUtil', conditions: ['Combination', 'Full'] },
           { control: 'CanVenStFem', parentControl: 'CPBUtil', conditions: ['Combination', 'Full'] },
           { control: 'CanVenStJug', parentControl: 'CPBUtil', conditions: ['Combination', 'Full'] },
           { control: 'CanVenStRtA', parentControl: 'CPBUtil', conditions: ['Combination', 'Full'] },
           { control: 'CanVenStLfA', parentControl: 'CPBUtil', conditions: ['Combination', 'Full'] },
           { control: 'CanVenStPulm', parentControl: 'CPBUtil', conditions: ['Combination', 'Full'] },
           { control: 'CanVenStBi', parentControl: 'CPBUtil', conditions: ['Combination', 'Full'] },
           { control: 'CanVenStOth', parentControl: 'CPBUtil', conditions: ['Combination', 'Full'] },
           { control: 'PerfusTm', parentControl: 'CPBUtil', conditions: ['Combination', 'Full'] },

           { control: 'DHCATm', parentControl: 'CircArr', conditions: ['Yes'] },
           { control: 'CPerfUtil', parentControl: 'CircArr', conditions: ['Yes'] },
           { control: 'CPerfTime', parentControl: 'CPerfUtil', conditions: ['Yes'] },
           { control: 'CPerfTyp', parentControl: 'CPerfUtil', conditions: ['Yes'] },
           { control: 'TotCircArrTm', parentControl: 'CircArr', conditions: ['Yes'] },
           {
             control: 'XClampTm',
             parentControl: 'AortOccl',
             conditions: ['Aortic Crossclamp', 'Balloon Occlusion']
           },
           {
             control: 'CplegiaType',
             parentControl: 'CplegiaDeliv',
             conditions: ['Antegrade', 'Retrograde', 'Both']
           },
           { control: 'AsmtAoDxMeth', parentControl: 'AsmtAscAA', conditions: ['Yes'] },
           { control: 'AsmtAoDx', parentControl: 'AsmtAscAA', conditions: ['Yes'] },

           { control: 'IBldProd', parentControl: 'IBldProdRef', conditions: ['No'] },
           { control: 'IBdRBCU', parentControl: 'IBldProd', conditions: ['Yes'] },
           { control: 'IBdFFPU', parentControl: 'IBldProd', conditions: ['Yes'] },
           { control: 'IBdPlatU', parentControl: 'IBldProd', conditions: ['Yes'] },
           { control: 'IBdCryoU', parentControl: 'IBldProd', conditions: ['Yes'] },

           { control: 'PRepAR', parentControl: 'InOpTEE', conditions: ['Yes'] },
           { control: 'PRepAGradM', parentControl: 'InOpTEE', conditions: ['Yes'] },
           { control: 'PRepAPVL', parentControl: 'InOpTEE', conditions: ['Yes'] },
           { control: 'PRepMR', parentControl: 'InOpTEE', conditions: ['Yes'] },
           { control: 'PRepMGradM', parentControl: 'InOpTEE', conditions: ['Yes'] },
           { control: 'PRepMPVL', parentControl: 'InOpTEE', conditions: ['Yes'] },
           { control: 'PRepTR', parentControl: 'InOpTEE', conditions: ['Yes'] },
           { control: 'PRepTGradM', parentControl: 'InOpTEE', conditions: ['Yes'] },
           { control: 'PRepTPVL', parentControl: 'InOpTEE', conditions: ['Yes'] },
           { control: 'PPEFMeas', parentControl: 'InOpTEE', conditions: ['Yes'] },
           { control: 'PPEF', parentControl: 'InOpTEE', conditions: ['Yes'] }
         ],
         sectionJ: [
           { control: 'IMAUsed', parentControl: 'I:OpCAB', conditions: ['!', 'No'] },
           { control: 'NoIMARsn', parentControl: 'IMAUsed', conditions: ['No'] },
           { control: 'NumIMADA', parentControl: 'IMAUsed', conditions: ['Yes'] },
           { control: 'LeftIMA', parentControl: 'IMAUsed', conditions: ['Yes'] },
           {
             control: 'LIMAHarvTech',
             parentControl: 'LeftIMA',
             conditions: ['Yes, pedicle', 'Yes, skeletonized']
           },
           { control: 'RightIMA', parentControl: 'IMAUsed', conditions: ['Yes'] },
           {
             control: 'RIMAHarvTech',
             parentControl: 'RightIMA',
             conditions: ['Yes, pedicle', 'Yes, skeletonized']
           },
           { control: 'RadialArtUsed', parentControl: 'I:OpCAB', conditions: ['!', 'No'] },
           { control: 'NumRadDA', parentControl: 'RadialArtUsed', conditions: ['Yes'] },
           { control: 'RadHTech', parentControl: 'RadialArtUsed', conditions: ['Yes'] },
           { control: 'RadHarvPrepTm', parentControl: 'RadialArtUsed', conditions: ['Yes'] },
           { control: 'VenousCondUsed', parentControl: 'I:OpCAB', conditions: ['!', 'No'] },
           { control: 'DistVein', parentControl: 'VenousCondUsed', conditions: ['Yes'] },
           { control: 'DistVeinHTech', parentControl: 'VenousCondUsed', conditions: ['Yes'] },
           { control: 'SaphHarPrepTm', parentControl: 'VenousCondUsed', conditions: ['Yes'] },
           { control: 'J:numDistAnas', parentControl: 'I:OpCAB', conditions: ['!', 'No'] },
           { control: 'NumOArtD', parentControl: 'I:OpCAB', conditions: ['!', 'No'] },
           { control: 'NumArtVenComp', parentControl: 'I:OpCAB', conditions: ['!', 'No'] },
           { control: 'NumVenArtComp', parentControl: 'I:OpCAB', conditions: ['!', 'No'] },
           { control: 'NumArtArtComp', parentControl: 'I:OpCAB', conditions: ['!', 'No'] },
           { control: 'ProxTech', parentControl: 'I:OpCAB', conditions: ['!', 'No'] },

           { control: 'J:cabg1', parentControl: 'I:OpCAB', conditions: ['!', 'No'] },
           { control: 'CAB01', parentControl: 'I:OpCAB', conditions: ['!', 'No'] },
           { control: 'CABDistSite01', parentControl: 'CAB01', conditions: ['Yes'] },
           { control: 'CABProximalSite01', parentControl: 'CAB01', conditions: ['Yes'] },
           { control: 'CABConduit01', parentControl: 'CAB01', conditions: ['Yes'] },
           { control: 'CABDistPos01', parentControl: 'CAB01', conditions: ['Yes'] },
           { control: 'CABEndArt01', parentControl: 'CAB01', conditions: ['Yes'] },
           { control: 'CABVeinPatAng01', parentControl: 'CAB01', conditions: ['Yes'] },

           { control: 'J:cabg2', parentControl: 'CAB01', conditions: ['Yes'] },
           { control: 'CAB02', parentControl: 'CAB01', conditions: ['Yes'] },
           { control: 'CABDistSite02', parentControl: 'CAB02', conditions: ['Yes'] },
           { control: 'CABProximalSite02', parentControl: 'CAB02', conditions: ['Yes'] },
           { control: 'CABConduit02', parentControl: 'CAB02', conditions: ['Yes'] },
           { control: 'CABDistPos02', parentControl: 'CAB02', conditions: ['Yes'] },
           { control: 'CABEndArt02', parentControl: 'CAB02', conditions: ['Yes'] },
           { control: 'CABVeinPatAng02', parentControl: 'CAB02', conditions: ['Yes'] },

           { control: 'J:cabg3', parentControl: 'CAB02', conditions: ['Yes'] },
           { control: 'CAB03', parentControl: 'CAB02', conditions: ['Yes'] },
           { control: 'CABDistSite03', parentControl: 'CAB03', conditions: ['Yes'] },
           { control: 'CABProximalSite03', parentControl: 'CAB03', conditions: ['Yes'] },
           { control: 'CABConduit03', parentControl: 'CAB03', conditions: ['Yes'] },
           { control: 'CABDistPos03', parentControl: 'CAB03', conditions: ['Yes'] },
           { control: 'CABEndArt03', parentControl: 'CAB03', conditions: ['Yes'] },
           { control: 'CABVeinPatAng03', parentControl: 'CAB03', conditions: ['Yes'] },

           { control: 'J:cabg4', parentControl: 'CAB03', conditions: ['Yes'] },
           { control: 'CAB04', parentControl: 'CAB03', conditions: ['Yes'] },
           { control: 'CABDistSite04', parentControl: 'CAB04', conditions: ['Yes'] },
           { control: 'CABProximalSite04', parentControl: 'CAB04', conditions: ['Yes'] },
           { control: 'CABConduit04', parentControl: 'CAB04', conditions: ['Yes'] },
           { control: 'CABDistPos04', parentControl: 'CAB04', conditions: ['Yes'] },
           { control: 'CABEndArt04', parentControl: 'CAB04', conditions: ['Yes'] },
           { control: 'CABVeinPatAng04', parentControl: 'CAB04', conditions: ['Yes'] },

           { control: 'J:cabg5', parentControl: 'CAB04', conditions: ['Yes'] },
           { control: 'CAB05', parentControl: 'CAB04', conditions: ['Yes'] },
           { control: 'CABDistSite05', parentControl: 'CAB05', conditions: ['Yes'] },
           { control: 'CABProximalSite05', parentControl: 'CAB05', conditions: ['Yes'] },
           { control: 'CABConduit05', parentControl: 'CAB05', conditions: ['Yes'] },
           { control: 'CABDistPos05', parentControl: 'CAB05', conditions: ['Yes'] },
           { control: 'CABEndArt05', parentControl: 'CAB05', conditions: ['Yes'] },
           { control: 'CABVeinPatAng05', parentControl: 'CAB05', conditions: ['Yes'] },

           { control: 'J:cabg6', parentControl: 'CAB05', conditions: ['Yes'] },
           { control: 'CAB06', parentControl: 'CAB05', conditions: ['Yes'] },
           { control: 'CABDistSite06', parentControl: 'CAB06', conditions: ['Yes'] },
           { control: 'CABProximalSite06', parentControl: 'CAB06', conditions: ['Yes'] },
           { control: 'CABConduit06', parentControl: 'CAB06', conditions: ['Yes'] },
           { control: 'CABDistPos06', parentControl: 'CAB06', conditions: ['Yes'] },
           { control: 'CABEndArt06', parentControl: 'CAB06', conditions: ['Yes'] },
           { control: 'CABVeinPatAng06', parentControl: 'CAB06', conditions: ['Yes'] },

           { control: 'J:cabg7', parentControl: 'CAB06', conditions: ['Yes'] },
           { control: 'CAB07', parentControl: 'CAB06', conditions: ['Yes'] },
           { control: 'CABDistSite07', parentControl: 'CAB07', conditions: ['Yes'] },
           { control: 'CABProximalSite07', parentControl: 'CAB07', conditions: ['Yes'] },
           { control: 'CABConduit07', parentControl: 'CAB07', conditions: ['Yes'] },
           { control: 'CABDistPos07', parentControl: 'CAB07', conditions: ['Yes'] },
           { control: 'CABEndArt07', parentControl: 'CAB07', conditions: ['Yes'] },
           { control: 'CABVeinPatAng07', parentControl: 'CAB07', conditions: ['Yes'] },

           { control: 'J:cabg8', parentControl: 'CAB07', conditions: ['Yes'] },
           { control: 'CAB08', parentControl: 'CAB07', conditions: ['Yes'] },
           { control: 'CABDistSite08', parentControl: 'CAB08', conditions: ['Yes'] },
           { control: 'CABProximalSite08', parentControl: 'CAB08', conditions: ['Yes'] },
           { control: 'CABConduit08', parentControl: 'CAB08', conditions: ['Yes'] },
           { control: 'CABDistPos08', parentControl: 'CAB08', conditions: ['Yes'] },
           { control: 'CABEndArt08', parentControl: 'CAB08', conditions: ['Yes'] },
           { control: 'CABVeinPatAng08', parentControl: 'CAB08', conditions: ['Yes'] },

           { control: 'J:cabg9', parentControl: 'CAB08', conditions: ['Yes'] },
           { control: 'CAB09', parentControl: 'CAB08', conditions: ['Yes'] },
           { control: 'CABDistSite09', parentControl: 'CAB09', conditions: ['Yes'] },
           { control: 'CABProximalSite09', parentControl: 'CAB09', conditions: ['Yes'] },
           { control: 'CABConduit09', parentControl: 'CAB09', conditions: ['Yes'] },
           { control: 'CABDistPos09', parentControl: 'CAB09', conditions: ['Yes'] },
           { control: 'CABEndArt09', parentControl: 'CAB09', conditions: ['Yes'] },
           { control: 'CABVeinPatAng09', parentControl: 'CAB09', conditions: ['Yes'] },

           { control: 'J:cabg10', parentControl: 'CAB09', conditions: ['Yes'] },
           { control: 'CAB10', parentControl: 'CAB09', conditions: ['Yes'] },
           { control: 'CABDistSite10', parentControl: 'CAB10', conditions: ['Yes'] },
           { control: 'CABProximalSite10', parentControl: 'CAB10', conditions: ['Yes'] },
           { control: 'CABConduit10', parentControl: 'CAB10', conditions: ['Yes'] },
           { control: 'CABDistPos10', parentControl: 'CAB10', conditions: ['Yes'] },
           { control: 'CABEndArt10', parentControl: 'CAB10', conditions: ['Yes'] },
           { control: 'CABVeinPatAng10', parentControl: 'CAB10', conditions: ['Yes'] }
         ],
         sectionK: [
           { control: 'ValExp', parentControl: 'I:OpValve', conditions: ['Yes'] },
           { control: 'ValExpPos', parentControl: 'ValExp', conditions: ['Yes'] },
           { control: 'ValExpTyp', parentControl: 'ValExp', conditions: ['Yes'] },
           { control: 'ValExpEt', parentControl: 'ValExp', conditions: ['Yes'] },
           { control: 'ValExpDevKnown', parentControl: 'ValExp', conditions: ['Yes'] },
           { control: 'ValExpDev', parentControl: 'ValExpDevKnown', conditions: ['Yes'] },
           { control: 'ValExpUDI', parentControl: 'ValExpDevKnown', conditions: ['Yes'] },
           { control: 'ValExp2', parentControl: 'ValExp', conditions: ['Yes'] },
           { control: 'ValExpPos2', parentControl: 'ValExp2', conditions: ['Yes'] },
           { control: 'ValExpTyp2', parentControl: 'ValExp2', conditions: ['Yes'] },
           { control: 'ValExpEt2', parentControl: 'ValExp2', conditions: ['Yes'] },
           { control: 'ValExpDevKnown2', parentControl: 'ValExp2', conditions: ['Yes'] },
           { control: 'ValExpDev2', parentControl: 'ValExpDevKnown2', conditions: ['Yes'] },
           { control: 'ValExpUDI2', parentControl: 'ValExpDevKnown2', conditions: ['Yes'] },

           // AORTIC VALVE
           { control: 'VSAV', parentControl: 'I:OpValve', conditions: ['Yes'] },
           { control: 'VSAVPr', parentControl: 'VSAV', conditions: ['!', 'No'] },
           { control: 'VSTCV', parentControl: 'VSAVPr', conditions: ['Replacement'] },
           { control: 'VSTCVR', parentControl: 'VSTCV', conditions: ['Yes'] },
           { control: 'VSAVSurgRep', parentControl: 'VSAVPr', conditions: ['Replacement'] },
           { control: 'VSAVSurgType', parentControl: 'VSAVSurgRep', conditions: ['Yes'] },
           { control: 'VSAVSurgBioT', parentControl: 'VSAVSurgType', conditions: ['Bioprosthetic'] },

           { control: 'K:repairType', parentControl: 'VSAVPr', conditions: ['Repair/Reconstruction'] },
           { control: 'VSAVRComA', parentControl: 'VSAVPr', conditions: ['Repair/Reconstruction'] },
           { control: 'VSAVRExSutAn', parentControl: 'VSAVPr', conditions: ['Repair/Reconstruction'] },
           { control: 'VSAVRLPlic', parentControl: 'VSAVPr', conditions: ['Repair/Reconstruction'] },
           { control: 'VSAVRNodRel', parentControl: 'VSAVPr', conditions: ['Repair/Reconstruction'] },
           { control: 'VSAVRPTFE', parentControl: 'VSAVPr', conditions: ['Repair/Reconstruction'] },
           { control: 'VSAVRComRS', parentControl: 'VSAVPr', conditions: ['Repair/Reconstruction'] },
           { control: 'VSAVRRaphe', parentControl: 'VSAVPr', conditions: ['Repair/Reconstruction'] },
           { control: 'VSAVRRingA', parentControl: 'VSAVPr', conditions: ['Repair/Reconstruction'] },
           { control: 'VSAVRRingATy', parentControl: 'VSAVRRingA', conditions: ['Yes'] },
           { control: 'VSAVRLResect', parentControl: 'VSAVPr', conditions: ['Repair/Reconstruction'] },
           { control: 'VSAVRLeafShav', parentControl: 'VSAVPr', conditions: ['Repair/Reconstruction'] },
           { control: 'VSAVRLPPatch', parentControl: 'VSAVPr', conditions: ['Repair/Reconstruction'] },
           { control: 'VSAVRDeb', parentControl: 'VSAVPr', conditions: ['Repair/Reconstruction'] },
           { control: 'VSAVRPeriLeak', parentControl: 'VSAVPr', conditions: ['Repair/Reconstruction'] },
           { control: 'AnlrEnl', parentControl: 'VSAV', conditions: ['!', 'No'] },
           { control: 'AnlrEnlTech', parentControl: 'AnlrEnl', conditions: ['Yes'] },
           { control: 'VSAVRoot', parentControl: 'VSAV', conditions: ['!', 'No'] },
           { control: 'K:rootProcedure', parentControl: 'VSAV', conditions: ['!', 'No'] },
           { control: 'VSAVRootOReimp', parentControl: 'VSAVRoot', conditions: ['Yes'] },
           { control: 'VSAVRootOReimpTy', parentControl: 'VSAVRootOReimp', conditions: ['Yes'] },
           { control: 'VSAVRepBioTy', parentControl: 'VSAVRootOReimpTy', conditions: ['Bioprosthetic'] },
           { control: 'VSAVSparRt', parentControl: 'VSAVRoot', conditions: ['Yes'] },
           { control: 'VSAVSparRtOp', parentControl: 'VSAVSparRt', conditions: ['Yes'] },
           { control: 'VSAVRootRecon', parentControl: 'VSAVRoot', conditions: ['Yes'] },
           { control: 'VSAVPat', parentControl: 'VSAV', conditions: ['!', 'No'] },
           { control: 'VSAVPatTy', parentControl: 'VSAVPat', conditions: ['Yes'] },
           { control: 'AorticImplant', parentControl: 'VSAV', conditions: ['!', 'No'] },
           { control: 'K:AVimplant', parentControl: 'VSAV', conditions: ['!', 'No'] },
           { control: 'VSAoIm', parentControl: 'AorticImplant', conditions: ['Yes'] },
           { control: 'VSAoImSz', parentControl: 'AorticImplant', conditions: ['Yes'] },
           { control: 'VSAoImUDI', parentControl: 'AorticImplant', conditions: ['Yes'] },

           // MITRAL VALVE
           { control: 'VSMV', parentControl: 'I:OpValve', conditions: ['Yes'] },
           { control: 'VSMVPr', parentControl: 'VSMV', conditions: ['!', 'No'] },
           { control: 'VSMVRepApp', parentControl: 'VSMVPr', conditions: ['Repair'] },
           { control: 'VSMitRAnnulo', parentControl: 'VSMVRepApp', conditions: ['Surgical'] },

           //  LEAFLET RESECTION
           { control: 'VSMitRLeafRes', parentControl: 'VSMVRepApp', conditions: ['Surgical'] },
           { control: 'VSLeafResTyp', parentControl: 'VSMitRLeafRes', conditions: ['Yes'] },
           { control: 'K:resectLoc', parentControl: 'VSMitRLeafRes', conditions: ['Yes'] },
           { control: 'VSLeafAntRes', parentControl: 'VSMitRLeafRes', conditions: ['Yes'] },
           { control: 'VSLeafAntResLocD', parentControl: 'VSLeafAntRes', conditions: ['Yes'] },
           { control: 'K:antLeafRect', parentControl: 'VSLeafAntResLocD', conditions: ['Yes'] },
           { control: 'VSLeafAntResA1', parentControl: 'VSLeafAntResLocD', conditions: ['Yes'] },
           { control: 'VSLeafAntResA2', parentControl: 'VSLeafAntResLocD', conditions: ['Yes'] },
           { control: 'VSLeafAntResA3', parentControl: 'VSLeafAntResLocD', conditions: ['Yes'] },
           { control: 'VSLeafPostRes', parentControl: 'VSMitRLeafRes', conditions: ['Yes'] },
           { control: 'VSLeafPostResLocD', parentControl: 'VSLeafPostRes', conditions: ['Yes'] },
           { control: 'K:postLeafRect', parentControl: 'VSLeafPostResLocD', conditions: ['Yes'] },
           { control: 'VSLeafPostResP1', parentControl: 'VSLeafPostResLocD', conditions: ['Yes'] },
           { control: 'VSLeafPostResP2', parentControl: 'VSLeafPostResLocD', conditions: ['Yes'] },
           { control: 'VSLeafPostResP3', parentControl: 'VSLeafPostResLocD', conditions: ['Yes'] },
           { control: 'VSLeafComRes', parentControl: 'VSMitRLeafRes', conditions: ['Yes'] },
           { control: 'VSLeafComResLoc', parentControl: 'VSLeafComRes', conditions: ['Yes'] },

           //  NEOCORDS (PTFE)
           { control: 'VSMitRPTFE', parentControl: 'VSMVRepApp', conditions: ['Surgical'] },
           { control: 'K:neoLoc', parentControl: 'VSMitRPTFE', conditions: ['Yes'] },
           { control: 'VSNeoAnt', parentControl: 'VSMitRPTFE', conditions: ['Yes'] },
           { control: 'VSNeoAntLocD', parentControl: 'VSNeoAnt', conditions: ['Yes'] },
           { control: 'K:antNeoLoc', parentControl: 'VSNeoAntLocD', conditions: ['Yes'] },
           { control: 'VSNeoAntA1', parentControl: 'VSNeoAntLocD', conditions: ['Yes'] },
           { control: 'VSNeoAntA2', parentControl: 'VSNeoAntLocD', conditions: ['Yes'] },
           { control: 'VSNeoAntA3', parentControl: 'VSNeoAntLocD', conditions: ['Yes'] },
           { control: 'VSNeoPost', parentControl: 'VSMitRPTFE', conditions: ['Yes'] },
           { control: 'VSNeoPostLocD', parentControl: 'VSNeoPost', conditions: ['Yes'] },
           { control: 'K:postNeoLoc', parentControl: 'VSNeoPostLocD', conditions: ['Yes'] },
           { control: 'VSNeoPostP1', parentControl: 'VSNeoPostLocD', conditions: ['Yes'] },
           { control: 'VSNeoPostP2', parentControl: 'VSNeoPostLocD', conditions: ['Yes'] },
           { control: 'VSNeoPostP3', parentControl: 'VSNeoPostLocD', conditions: ['Yes'] },
           { control: 'VSNeoCom', parentControl: 'VSMitRPTFE', conditions: ['Yes'] },
           { control: 'VSNeoComLoc', parentControl: 'VSNeoCom', conditions: ['Yes'] },

           //  CHORDAL/LEAFLET TRANSFER
           { control: 'VSMitRChord', parentControl: 'VSMVRepApp', conditions: ['Surgical'] },
           { control: 'K:chorLeafLoc', parentControl: 'VSMitRChord', conditions: ['Yes'] },
           { control: 'VSChorLfAnt', parentControl: 'VSMitRChord', conditions: ['Yes'] },
           { control: 'VSChorLfAntLocD', parentControl: 'VSChorLfAnt', conditions: ['Yes'] },
           { control: 'K:antChorLfLoc', parentControl: 'VSChorLfAntLocD', conditions: ['Yes'] },
           { control: 'VSChorLfAntA1', parentControl: 'VSChorLfAntLocD', conditions: ['Yes'] },
           { control: 'VSChorLfAntA2', parentControl: 'VSChorLfAntLocD', conditions: ['Yes'] },
           { control: 'VSChorLfAntA3', parentControl: 'VSChorLfAntLocD', conditions: ['Yes'] },
           { control: 'VSChorLfPost', parentControl: 'VSMitRChord', conditions: ['Yes'] },
           { control: 'VSChorLfPostLocD', parentControl: 'VSChorLfPost', conditions: ['Yes'] },
           { control: 'K:postChorLfLoc', parentControl: 'VSChorLfPostLocD', conditions: ['Yes'] },
           { control: 'VSChorLfPostP1', parentControl: 'VSChorLfPostLocD', conditions: ['Yes'] },
           { control: 'VSChorLfPostP2', parentControl: 'VSChorLfPostLocD', conditions: ['Yes'] },
           { control: 'VSChorLfPostP3', parentControl: 'VSChorLfPostLocD', conditions: ['Yes'] },
           { control: 'VSChorLfCom', parentControl: 'VSMitRChord', conditions: ['Yes'] },
           { control: 'VSChorLfComLoc', parentControl: 'VSChorLfCom', conditions: ['Yes'] },

           { control: 'VSMitRFold', parentControl: 'VSMVPr', conditions: ['Repair'] },
           { control: 'VSMitRSlidP', parentControl: 'VSMVPr', conditions: ['Repair'] },
           { control: 'VSMitRADecalc', parentControl: 'VSMVPr', conditions: ['Repair'] },
           { control: 'VSMitRLeafERP', parentControl: 'VSMVPr', conditions: ['Repair'] },
           { control: 'VSMitRLeafERPLoc', parentControl: 'VSMitRLeafERP', conditions: ['Yes'] },
           { control: 'VSMitREdge', parentControl: 'VSMVPr', conditions: ['Repair'] },
           { control: 'VSMitRMitComm', parentControl: 'VSMVPr', conditions: ['Repair'] },
           { control: 'VSMitRMitCplasty', parentControl: 'VSMVPr', conditions: ['Repair'] },
           { control: 'VSMitRMitCleft', parentControl: 'VSMVPr', conditions: ['Repair'] },
           { control: 'VSMitParaprosLeak', parentControl: 'VSMVPr', conditions: ['Repair'] },

           { control: 'MitralIntent', parentControl: 'VSMVPr', conditions: ['Replacement'] },
           { control: 'VSChorPres', parentControl: 'VSMVPr', conditions: ['Replacement'] },
           { control: 'VSTCVMit', parentControl: 'VSMVPr', conditions: ['Replacement'] },

           { control: 'MitralImplant', parentControl: 'VSMV', conditions: ['!', 'No'] },
           { control: 'MitralImplantTy', parentControl: 'MitralImplant', conditions: ['Yes'] },
           { control: 'VSMiIm', parentControl: 'MitralImplant', conditions: ['Yes'] },
           { control: 'VSMiImSz', parentControl: 'MitralImplant', conditions: ['Yes'] },
           { control: 'VSMiImUDI', parentControl: 'MitralImplant', conditions: ['Yes'] },

           //  TRICUSPID VALVE
           { control: 'VSTV', parentControl: 'I:OpValve', conditions: ['Yes'] },
           { control: 'VSTVPr', parentControl: 'VSTV', conditions: ['!', 'No'] },
           { control: 'VSTrRepAnnulo', parentControl: 'VSTVPr', conditions: ['Repair'] },
           { control: 'OpTricusAnTy', parentControl: 'VSTrRepAnnulo', conditions: ['Yes'] },
           { control: 'VSTrLeafRes', parentControl: 'VSTVPr', conditions: ['Repair'] },
           { control: 'VSTCVTri', parentControl: 'VSTVPr', conditions: ['Replacement'] },
           { control: 'TricuspidImplant', parentControl: 'VSTV', conditions: ['!', 'No'] },
           { control: 'TricusImplantTy', parentControl: 'TricuspidImplant', conditions: ['Yes'] },
           { control: 'VSTrIm', parentControl: 'TricuspidImplant', conditions: ['Yes'] },
           { control: 'VSTrImSz', parentControl: 'TricuspidImplant', conditions: ['Yes'] },
           { control: 'VSTrImUDI', parentControl: 'TricuspidImplant', conditions: ['Yes'] },

           //  PULMONIC VALVE
           { control: 'VSPV', parentControl: 'I:OpValve', conditions: ['Yes'] },
           { control: 'OpPulm', parentControl: 'VSPV', conditions: ['!', 'No'] },
           { control: 'VSTCVPu', parentControl: 'OpPulm', conditions: ['Replacement'] },
           { control: 'PulmonicImplant', parentControl: 'VSPV', conditions: ['!', 'No'] },
           { control: 'VSPuTypeImp', parentControl: 'PulmonicImplant', conditions: ['!', 'No'] },
           { control: 'VSPuImpMat', parentControl: 'VSPuTypeImp', conditions: ['Surgeon Fashioned'] },
           { control: 'PulmonicImplantTy', parentControl: 'VSPuTypeImp', conditions: ['Commercially Supplied'] },
           { control: 'VSPuIm', parentControl: 'PulmonicImplant', conditions: ['Yes'] },
           { control: 'VSPuImSz', parentControl: 'PulmonicImplant', conditions: ['Yes'] },
           { control: 'VSPuImUDI', parentControl: 'PulmonicImplant', conditions: ['Yes'] }
         ],
         sectionL: [
           { control: 'IABPWhen', parentControl: 'IABP', conditions: ['Yes'] },
           { control: 'IABPInd', parentControl: 'IABP', conditions: ['Yes'] },
           { control: 'CathBasAssistTy', parentControl: 'CathBasAssist', conditions: ['Yes'] },
           { control: 'CathBasAssistWhen', parentControl: 'CathBasAssist', conditions: ['Yes'] },
           { control: 'CathBasAssistInd', parentControl: 'CathBasAssist', conditions: ['Yes'] },
           { control: 'ECMOWhen', parentControl: 'ECMO', conditions: ['!', 'No'] },
           { control: 'ECMOInd', parentControl: 'ECMO', conditions: ['!', 'No'] }
         ],
         sectionL2: [
           { control: 'PrevVADF', parentControl: 'PrevVAD', conditions: ['Yes'] },
           { control: 'PrevVADD', parentControl: 'PrevVAD', conditions: ['Yes'] },
           { control: 'PrevVADIn', parentControl: 'PrevVAD', conditions: ['Yes'] },
           { control: 'PrevVADTy', parentControl: 'PrevVAD', conditions: ['Yes'] },
           { control: 'PrevVADDevice', parentControl: 'PrevVAD', conditions: ['Yes'] },
           { control: 'PrevVADUDI', parentControl: 'PrevVAD', conditions: ['Yes'] },
           { control: 'PrevVADExp', parentControl: 'PrevVAD', conditions: ['Yes'] },
           {
             control: 'PrevVADExpRsn',
             parentControl: 'PrevVADExp',
             conditions: ['Yes, not during this procedure', 'Yes, during this procedure']
           },
           {
             control: 'PrevVADExpDt',
             parentControl: 'PrevVADExp',
             conditions: ['Yes, not during this procedure']
           },

           { control: 'L2:vadImplant', parentControl: 'VADImp', conditions: ['Yes'] },
           { control: 'L2:vad1', parentControl: 'VADImp', conditions: ['Yes'] },
           { control: 'VImp', parentControl: 'VADImp', conditions: ['Yes'] },
           { control: 'VADImpTmg', parentControl: 'VImp', conditions: ['Yes'] },
           { control: 'VImpDt', parentControl: 'VImp', conditions: ['Yes'] },
           { control: 'VADInd', parentControl: 'VImp', conditions: ['Yes'] },
           { control: 'VImpTy', parentControl: 'VImp', conditions: ['Yes'] },
           { control: 'VProdTy', parentControl: 'VImp', conditions: ['Yes'] },
           { control: 'VImpUDI', parentControl: 'VImp', conditions: ['Yes'] },
           { control: 'VExp', parentControl: 'VImp', conditions: ['Yes'] },
           {
             control: 'VExpRsn',
             parentControl: 'VExp',
             conditions: ['Yes, not during this procedure', 'Yes, during this procedure']
           },
           { control: 'VExpDt', parentControl: 'VExp', conditions: ['Yes, not during this procedure'] },

           { control: 'L2:vad2', parentControl: 'VImp', conditions: ['Yes'] },
           { control: 'VImp2', parentControl: 'VImp', conditions: ['Yes'] },
           { control: 'VADImpTmg2', parentControl: 'VImp2', conditions: ['Yes'] },
           { control: 'VImpDt2', parentControl: 'VImp2', conditions: ['Yes'] },
           { control: 'VADInd2', parentControl: 'VImp2', conditions: ['Yes'] },
           { control: 'VImpTy2', parentControl: 'VImp2', conditions: ['Yes'] },
           { control: 'VProdTy2', parentControl: 'VImp2', conditions: ['Yes'] },
           { control: 'VImpUDI2', parentControl: 'VImp2', conditions: ['Yes'] },
           { control: 'VExp2', parentControl: 'VImp2', conditions: ['Yes'] },
           {
             control: 'VExpRsn2',
             parentControl: 'VExp2',
             conditions: ['Yes, not during this procedure', 'Yes, during this procedure']
           },
           { control: 'VExpDt2', parentControl: 'VExp2', conditions: ['Yes, not during this procedure'] },

           { control: 'L2:vad3', parentControl: 'VImp2', conditions: ['Yes'] },
           { control: 'VImp3', parentControl: 'VImp2', conditions: ['Yes'] },
           { control: 'VADImpTmg3', parentControl: 'VImp3', conditions: ['Yes'] },
           { control: 'VImpDt3', parentControl: 'VImp3', conditions: ['Yes'] },
           { control: 'VADInd3', parentControl: 'VImp3', conditions: ['Yes'] },
           { control: 'VImpTy3', parentControl: 'VImp3', conditions: ['Yes'] },
           { control: 'VProdTy3', parentControl: 'VImp3', conditions: ['Yes'] },
           { control: 'VImpUDI3', parentControl: 'VImp3', conditions: ['Yes'] },
           { control: 'VExp3', parentControl: 'VImp3', conditions: ['Yes'] },
           {
             control: 'VExpRsn3',
             parentControl: 'VExp3',
             conditions: ['Yes, not during this procedure', 'Yes, during this procedure']
           },
           { control: 'VExpDt3', parentControl: 'VExp3', conditions: ['Yes, not during this procedure'] }
         ],
         sectionM: [
           { control: 'OCarASDPFO', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCarASDSec', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCarAFibIntraLes', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCarAFibEpLes', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCarAAProc', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCarAAMeth', parentControl: 'OCarAAProc', conditions: ['!', 'No'] },
           {
             control: 'OCarAAModel',
             parentControl: 'OCarAAMeth',
             conditions: ['Epicardially applied occlusion device']
           },
           {
             control: 'OCarAAUDI',
             parentControl: 'OCarAAMeth',
             conditions: ['Epicardially applied occlusion device']
           },
           { control: 'OCarACD', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCarLeadInsert', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCarACDLE', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCarCong', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCarLVA', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCarStemCell', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCPulThromDis', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCarSubaStenRes', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCarSubaStenResTy', parentControl: 'OCarSubaStenRes', conditions: ['Yes'] },
           { control: 'OCarSVR', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCarLasr', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCTumor', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCarCrTx', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCarTrma', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCarVSD', parentControl: 'I:OpOCard', conditions: ['!', 'No'] },
           { control: 'OCarOthr', parentControl: 'I:OpOCard', conditions: ['!', 'No'] }
         ],
         sectionM1: [
           { control: 'OCarAFibLesLoc', parentControl: 'I:AFibProc', conditions: ['Yes'] },
           { control: 'M1:methLesCrea', parentControl: 'I:AFibProc', conditions: ['Yes'] },
           { control: 'OCarAFibMethRad', parentControl: 'I:AFibProc', conditions: ['Yes'] },
           { control: 'OCarAFibMethRadBi', parentControl: 'OCarAFibMethRad', conditions: ['Yes'] },
           { control: 'OCarAFibMethCAS', parentControl: 'I:AFibProc', conditions: ['Yes'] },
           { control: 'OCarAFibMethCryo', parentControl: 'I:AFibProc', conditions: ['Yes'] },
           { control: 'OCarLesDoc', parentControl: 'I:AFibProc', conditions: ['Yes'] },
           { control: 'M1:afib1Fig', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'M1:afib2Fig', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFibLes1', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFibLes2', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFibLes3a', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFibLes3b', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFibLes4', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFibLes5', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFibLes6', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFibLes7', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFibLes8', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFibLes9', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFibLes10', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFibLes11', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFibLes12', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFibLes13', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFibLes14', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFibLes15a', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFibLes15b', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
           { control: 'AFitLesCSL', parentControl: 'OCarLesDoc', conditions: ['Yes'] },
         ],
         sectionM2: [],
         sectionM3: [],
         sectionN: [],
         sectionO: [],
         sectionP: [],
         sectionQ: [],
         sectionR: []
       };
