// tslint:disable: variable-name
export const segmentNumbers = [
  '1 - pRCA',
  '2 - mRCA',
  '3 - dRCA',
  '4 - rPDA',
  '5 - rPAV',
  '6 - 1st RPL',
  '7 - 2nd RPL',
  '8 - 3rd RPL',
  '9 - pDSP',
  '10 - aMarg',
  '11a - Ostial LM',
  '11b - Mid-LM',
  '11c - Distal LM',
  '12 - pLAD',
  '13 - mLAD',
  '14 - dLAD',
  '15 - 1st Diag',
  '15a - Lat 1st Diag',
  '16 - 2nd Diag',
  '16a - Lat 2nd Diag',
  '17 - LAD SP',
  '18 - pCIRC',
  '19 - mCIRC',
  '19a - dCIRC',
  '20 - 1st OM',
  '20a - Lat 1st OM',
  '21 - 2nd OM',
  '21a - Lat 2nd OM',
  '22 - 3rd OM',
  '22a - Lat 3rd OM',
  '23 - CIRC AV',
  '24 - 1st LPL',
  '25 - 2nd LPL',
  '26 - 3rd LPL',
  '27 - LPDA',
  '28 - Ramus',
  '28a - Lat Ramus',
  '29 - 3rd Diag',
  '29a - Lat 3rd Diag'
];

export const deathCauses = [
  'Acute myocardial infarction',
  'Sudden cardiac death',
  'Heart failure',
  'Stroke',
  'Cardiovascular procedure',
  'Cardiovascular hemorrhage',
  'Other cardiovascular reason',
  'Pulmonary',
  'Renal',
  'Gastrointestinal',
  'Hepatobiliary',
  'Pancreatic',
  'Infection',
  'Inflammatory/Immunologic',
  'Hemorrhage',
  'Non-cardiovascular procedure or surgery',
  'Trauma',
  'Suicide',
  'Neurological',
  'Malignancy',
  'Other non-cardiovascular reason'
];

export const J_lesions = [
  [
    'LESION COUNTER 1',
    'HasLesion01',
    'SegmentID01',
    'CulpritArtery01',
    'StenosisPriorTreat01',
    'ChronicOcclusion01',
    'PreProcTIMI01',
    'PrevTreatedLesion01',
    'PrevTreatedLesionDate01',
    'PreviousStent01',
    'InRestenosis01',
    'InThrombosis01',
    'StentType01',
    'LesionGraft01',
    'LesionGraftType01',
    'LocGraft01',
    'NavGraftNatLes01',
    'LesionComplexity01',
    'LesionLength01',
    'SevereCalcification01',
    'BifurcationLesion01',
    'GuidewireLesion01',
    'DeviceDeployed01',
    'StenosisPostProc01',
    'PostProcTIMI01'
  ],
  [
    'LESION COUNTER 2',
    'HasLesion02',
    'SegmentID02',
    'CulpritArtery02',
    'StenosisPriorTreat02',
    'ChronicOcclusion02',
    'PreProcTIMI02',
    'PrevTreatedLesion02',
    'PrevTreatedLesionDate02',
    'PreviousStent02',
    'InRestenosis02',
    'InThrombosis02',
    'StentType02',
    'LesionGraft02',
    'LesionGraftType02',
    'LocGraft02',
    'NavGraftNatLes02',
    'LesionComplexity02',
    'LesionLength02',
    'SevereCalcification02',
    'BifurcationLesion02',
    'GuidewireLesion02',
    'DeviceDeployed02',
    'StenosisPostProc02',
    'PostProcTIMI02'
  ],
  [
    'LESION COUNTER 3',
    'HasLesion03',
    'SegmentID03',
    'CulpritArtery03',
    'StenosisPriorTreat03',
    'ChronicOcclusion03',
    'PreProcTIMI03',
    'PrevTreatedLesion03',
    'PrevTreatedLesionDate03',
    'PreviousStent03',
    'InRestenosis03',
    'InThrombosis03',
    'StentType03',
    'LesionGraft03',
    'LesionGraftType03',
    'LocGraft03',
    'NavGraftNatLes03',
    'LesionComplexity03',
    'LesionLength03',
    'SevereCalcification03',
    'BifurcationLesion03',
    'GuidewireLesion03',
    'DeviceDeployed03',
    'StenosisPostProc03',
    'PostProcTIMI03'
  ],
  [
    'LESION COUNTER 4',
    'HasLesion04',
    'SegmentID04',
    'CulpritArtery04',
    'StenosisPriorTreat04',
    'ChronicOcclusion04',
    'PreProcTIMI04',
    'PrevTreatedLesion04',
    'PrevTreatedLesionDate04',
    'PreviousStent04',
    'InRestenosis04',
    'InThrombosis04',
    'StentType04',
    'LesionGraft04',
    'LesionGraftType04',
    'LocGraft04',
    'NavGraftNatLes04',
    'LesionComplexity04',
    'LesionLength04',
    'SevereCalcification04',
    'BifurcationLesion04',
    'GuidewireLesion04',
    'DeviceDeployed04',
    'StenosisPostProc04',
    'PostProcTIMI04'
  ],
  [
    'LESION COUNTER 5',
    'HasLesion05',
    'SegmentID05',
    'CulpritArtery05',
    'StenosisPriorTreat05',
    'ChronicOcclusion05',
    'PreProcTIMI05',
    'PrevTreatedLesion05',
    'PrevTreatedLesionDate05',
    'PreviousStent05',
    'InRestenosis05',
    'InThrombosis05',
    'StentType05',
    'LesionGraft05',
    'LesionGraftType05',
    'LocGraft05',
    'NavGraftNatLes05',
    'LesionComplexity05',
    'LesionLength05',
    'SevereCalcification05',
    'BifurcationLesion05',
    'GuidewireLesion05',
    'DeviceDeployed05',
    'StenosisPostProc05',
    'PostProcTIMI05'
  ],
  [
    'LESION COUNTER 6',
    'HasLesion06',
    'SegmentID06',
    'CulpritArtery06',
    'StenosisPriorTreat06',
    'ChronicOcclusion06',
    'PreProcTIMI06',
    'PrevTreatedLesion06',
    'PrevTreatedLesionDate06',
    'PreviousStent06',
    'InRestenosis06',
    'InThrombosis06',
    'StentType06',
    'LesionGraft06',
    'LesionGraftType06',
    'LocGraft06',
    'NavGraftNatLes06',
    'LesionComplexity06',
    'LesionLength06',
    'SevereCalcification06',
    'BifurcationLesion06',
    'GuidewireLesion06',
    'DeviceDeployed06',
    'StenosisPostProc06',
    'PostProcTIMI06'
  ],
  [
    'LESION COUNTER 6',
    'HasLesion07',
    'SegmentID07',
    'CulpritArtery07',
    'StenosisPriorTreat07',
    'ChronicOcclusion07',
    'PreProcTIMI07',
    'PrevTreatedLesion07',
    'PrevTreatedLesionDate07',
    'PreviousStent07',
    'InRestenosis07',
    'InThrombosis07',
    'StentType07',
    'LesionGraft07',
    'LesionGraftType07',
    'LocGraft07',
    'NavGraftNatLes07',
    'LesionComplexity07',
    'LesionLength07',
    'SevereCalcification07',
    'BifurcationLesion07',
    'GuidewireLesion07',
    'DeviceDeployed07',
    'StenosisPostProc07',
    'PostProcTIMI07'
  ],
  [
    'LESION COUNTER 8',
    'HasLesion08',
    'SegmentID08',
    'CulpritArtery08',
    'StenosisPriorTreat08',
    'ChronicOcclusion08',
    'PreProcTIMI08',
    'PrevTreatedLesion08',
    'PrevTreatedLesionDate08',
    'PreviousStent08',
    'InRestenosis08',
    'InThrombosis08',
    'StentType08',
    'LesionGraft08',
    'LesionGraftType08',
    'LocGraft08',
    'NavGraftNatLes08',
    'LesionComplexity08',
    'LesionLength08',
    'SevereCalcification08',
    'BifurcationLesion08',
    'GuidewireLesion08',
    'DeviceDeployed08',
    'StenosisPostProc08',
    'PostProcTIMI08'
  ]
];

export const J_devices = [
  [
    'DEVICE COUNTER 1',
    'UseDevice01',
    'ICDevID01',
    'ICDevUDI01',
    'ICDevCounterAssn01',
    'DeviceDiameter01',
    'DeviceLength01'
  ],
  [
    'DEVICE COUNTER 2',
    'UseDevice02',
    'ICDevID02',
    'ICDevUDI02',
    'ICDevCounterAssn02',
    'DeviceDiameter02',
    'DeviceLength02'
  ],
  [
    'DEVICE COUNTER 3',
    'UseDevice03',
    'ICDevID03',
    'ICDevUDI03',
    'ICDevCounterAssn03',
    'DeviceDiameter03',
    'DeviceLength03'
  ],
  [
    'DEVICE COUNTER 4',
    'UseDevice04',
    'ICDevID04',
    'ICDevUDI04',
    'ICDevCounterAssn04',
    'DeviceDiameter04',
    'DeviceLength04'
  ],
  [
    'DEVICE COUNTER 5',
    'UseDevice05',
    'ICDevID05',
    'ICDevUDI05',
    'ICDevCounterAssn05',
    'DeviceDiameter05',
    'DeviceLength05'
  ],
  [
    'DEVICE COUNTER 6',
    'UseDevice06',
    'ICDevID06',
    'ICDevUDI06',
    'ICDevCounterAssn06',
    'DeviceDiameter06',
    'DeviceLength06'
  ],
  [
    'DEVICE COUNTER 7',
    'UseDevice07',
    'ICDevID07',
    'ICDevUDI07',
    'ICDevCounterAssn07',
    'DeviceDiameter07',
    'DeviceLength07'
  ],
  [
    'DEVICE COUNTER 8',
    'UseDevice08',
    'ICDevID08',
    'ICDevUDI08',
    'ICDevCounterAssn08',
    'DeviceDiameter08',
    'DeviceLength08'
  ],
  [
    'DEVICE COUNTER 9',
    'UseDevice09',
    'ICDevID09',
    'ICDevUDI09',
    'ICDevCounterAssn09',
    'DeviceDiameter09',
    'DeviceLength09'
  ],
  [
    'DEVICE COUNTER 10',
    'UseDevice10',
    'ICDevID10',
    'ICDevUDI10',
    'ICDevCounterAssn10',
    'DeviceDiameter10',
    'DeviceLength10'
  ]
];

export const K_procedureEvents = [
  ['Bleeding – Access Site', 'K_BleedingAccessSite', 'K_BleedingAccessSiteDT'],
  ['Bleeding – Gastrointestinal', 'K_BleedingGI', 'K_BleedingGIDT'],
  ['Bleeding – Genitourinary', 'K_BleedingGU', 'K_BleedingGUDT'],
  ['Bleeding – Hematoma at Access Site', 'K_BleedingHematoma', 'K_BleedingHematomaDT'],
  ['Bleeding – Other', 'K_BleedingOther', 'K_BleedingOtherDT'],
  ['Bleeding – Retroperitoneal', 'K_BleedingRetro', 'K_BleedingRetroDT'],
  ['Cardiac Arrest', 'K_CardiacArrest', 'K_CardiacArrestDT'],
  ['Cardiac Tamponade', 'K_CardiacTamponade', 'K_CardiacTamponadeDT'],
  ['Cardiogenic Shock', 'K_CardiogenicShock', 'K_CardiogenicShockDT'],
  ['Heart Failure', 'K_HeartFailure', 'K_HeartFailureDT'],
  ['New Requirement for Dialysis', 'K_NewDialysis', 'K_NewDialysisDT'],
  ['Other Vascular Complications Req Tx', 'K_OtherVascular', 'K_OtherVascularDT'],
  ['Stroke – Hemorrhagic', 'K_StrokeHemorrhage', 'K_StrokeHemorrhageDT'],
  ['Stroke – Ischemic', 'K_StrokeIschemic', 'K_StrokeIschemicDT'],
  ['Stroke – Undetermined', 'K_StrokeUndetermined', 'K_StrokeUndeterminedDT']
];

export const M_followUpEvents = [
  ['Bleeding Event', 'M_BleedingEvent', null, 'M_BleedingEventDT'],
  ['CABG: Bypass of stented lesion', 'M_CABGStent', 'M_CABGStentLesions', 'M_CABGStentDT'],
  ['CABG: Bypass of non-stented lesion', 'M_CABGNonStent', null, 'M_CABGNonStentDT'],
  ['Myocardial Infarction: NSTEMI', 'M_NSTEMI', null, 'M_NSTEMIDT'],
  ['Myocardial Infarction: Q-wave', 'M_Qwave', null, 'M_QwaveDT'],
  ['Myocardial Infarction: STEMI', 'M_STEMI', null, 'M_STEMIDT'],
  ['Myocardial Infarction: Type Unknown', 'M_MIUnknown', null, 'M_MIUnknownDT'],
  ['PCI of non-stented lesion', 'M_PCINonStent', null, 'M_PCINonStentDT'],
  ['PCI of stented lesion', 'M_PCIStent', 'M_PCIStentLesions', 'M_PCIStentDT'],
  ['Readmission: Non-PCI Related', 'M_Readmission', null, 'M_Readmission'],
  ['Stroke – Hemorrhagic', 'M_StrokeHemorrhage', null, 'M_StrokeHemorrhageDT'],
  ['Stroke – Ischemic', 'M_StrokeIschemic', null, 'M_StrokeIschemicDT'],
  ['Stroke – Undetermined', 'M_StrokeUndetermined', null, 'M_StrokeUndeterminedDT'],
  ['Thrombosis in stented lesion', 'M_ThrombosisStent', 'M_ThrombosisStentLesions', 'M_ThrombosisStentDT'],
  ['Thrombosis in non-stented lesion', 'M_ThrombosisNonStent', null, 'M_ThrombosisNonStentDT'],
];
// tslint:enable: variable-name
